In [1]:
# 1) Write a NumPy program to calculate the arithmetic mean, median, and standard deviation of array of numbers.

import numpy as np

num = [1, 4, 2, 6, 7, 9, 10]
mean = np.mean(num)
med = np.median(num)
stand = np.std(num)

print("\nmean: " + str(mean) + "\nmedian: " + str(med) + "\nstandard deviation: " + str(stand))


mean: 5.571428571428571
median: 6.0
standard deviation: 3.1558174334820746


In [2]:
# 2) Write a Python function that takes a Numpy array a and returns a new array b where each element of b is the cumulative sum of the corresponding element and all preceding elements of a. For example, if a = [1, 2, 3, 4, 5], then b = [1, 3, 6, 10, 15]

import numpy as np

a = [1, 2, 3, 4, 5]
b = np.cumsum(a)

print(b)

[ 1  3  6 10 15]


In [3]:
# 3) Write a program to reverse a NumPy array

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.flip(a)
print(b)

[5 4 3 2 1]


In [4]:
# 4) Write a program to convert a string element to uppercase, lowercase, capitalise the first letter, title-case and swapcase of a given NumPy array.

import numpy as np

a = np.array("bhargav jani")
b = str(a).upper()
c = str(a).lower()
d = str(a).capitalize()
e = str(a).title()

print(a)
print(b)
print(c)
print(d)
print(e)

bhargav jani
BHARGAV JANI
bhargav jani
Bhargav jani
Bhargav Jani


In [5]:
# 5) Write a program to repeat each of the elements five times for a given numpy array.
# Input = [‘a’,’hello’] output = [‘aaaaa’,’hellohellohellohellohello’]

import numpy as np

inp = ['a', 'hello']
out = np.char.multiply(inp, 5)

print(out)

['aaaaa' 'hellohellohellohellohello']


In [8]:
# 6) Write a program for changing the dimension of a NumPy array

import numpy as np

inp = [int(j) for j in input().split(" ")]

inp = np.array(inp)

print("change shape to :  ")
ls = [int(i) for i in input().split(" ")]

out = np.reshape(inp, tuple(ls))

print(out)

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
change shape to :  
5 3 3
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]]


In [14]:
# 7) Write a program for interchanging two axes of the NumPy array.

import numpy as np

n = int(input())
print()

inp = np.array([[int(i) for i in input().split(" ")] for i in range(n)])
out = np.swapaxes(inp, 0, 1)
print()
print(out)

4

1 2 3
4 5 6
7 8 9
9 8 6

[[1 4 7 9]
 [2 5 8 8]
 [3 6 9 6]]
