In [ ]:
# 1) Given a 2D array A, your task is to convert all rows to columns and columns to rows.
# # Input:
# # First line contains 2 space separated integers, N - total rows, M - total columns.
# # Each of the next N lines will contain M space separated integers.
# # Output:
# # Print M lines each containing N space separated integers.
# SAMPLE INPUT
# 3 5
# 13 4 8 14 1
# 9 6 3 7 21
# 5 12 17 9 3
# # SAMPLE OUTPUT
# 13 9 5
# 4 6 12
# 8 3 17
# 14 7 9
# 1 21 3

import numpy as np

arr_2d = np.array([
    [13, 4, 8, 14, 1],
    [9, 6, 3, 7, 21],
    [5, 12, 17, 9, 3]
])

print(arr_2d)

arr_tr = np.transpose(arr_2d)
print(arr_tr)

[[13  4  8 14  1]
 [ 9  6  3  7 21]
 [ 5 12 17  9  3]]
[[13  9  5]
 [ 4  6 12]
 [ 8  3 17]
 [14  7  9]
 [ 1 21  3]]


In [ ]:
# 2) Your program is to use the brute-force approach in order to find the Answer to Life, the Universe, and Everything.
# # All numbers at input are integers of one or two digits.
# # Sample Input:
# 1
# 2
# 88
# 42
# 99
# # sample Output:
# 1
# 2
# 88

numbers = [1, 2, 88, 42, 99]
outp = []
result = []
for num in numbers:
    if num == 42:
        result.append(num)
        break
    else:
      outp.append(num)

print(result)
print(outp)

[42]
[1, 2, 88]


In [ ]:
# 3) Filter only negative and zero in the list using list comprehension. numbers = [-4, -3, -1, 0, 2, 4, 6]

numbers = [-4, -3, -1, 0, 2, 4, 6]
neg_number = [i for i in numbers if i<=0]
print(neg_number)

[-4, -3, -1, 0]


In [ ]:
# 4) Flatten the following list of lists of lists to a one dimensional list :
# list_of_lists =[[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]] output : [1, 2, 3, 4, 5, 6, 7, 8, 9]

import numpy as np
list_of_lists =[[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]]
outp = np.array(list_of_lists).flatten()
print(outp)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# 5) Change the following list to a list of dictionaries:
# countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]] output: [{'country': 'FINLAND', 'city': 'HELSINKI'},
# {'country': 'SWEDEN', 'city': 'STOCKHOLM'}, {'country': 'NORWAY', 'city': 'OSLO'}]

countries = [[('Finland', 'Helsinki')], [('Sweden', 'Stockholm')], [('Norway', 'Oslo')]]
outp = []

for i in countries:
  for j in i:
    outp.append({"country": j[0], "city": j[1]})

print(outp)

[{'country': 'Finland', 'city': 'Helsinki'}, {'country': 'Sweden', 'city': 'Stockholm'}, {'country': 'Norway', 'city': 'Oslo'}]
